# Generated by Django 5.2.7 on 2025-10-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qantity',
            new_name='quantity',
        ),
    ]
